inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - rubocop-performance
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Naming/MethodName:
  Exclude:
    - 'app/helpers/**/*.rb'

Naming/VariableName:
  Exclude:
    - 'app/helpers/**/*.rb'

Naming/MethodParameterName:
  Exclude:
    - 'app/helpers/**/*.rb'
