name: Code style

on: [push]

jobs:
  ruby:
    name: "Ruby"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache Gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-no-dev-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: install dependencies
      run: |
        gem install bundler --no-doc
        bundle config path vendor/bundle
        bundle check || bundle install --without development --jobs 4 --retry 3

    - name: Run code style checks
      run:  bundle exec rubocop
