name: Yank gem from RubyGems.org

on:
  release:
    types: [published]

jobs:
  push:
    name: "Run gem yank"
    runs-on: ubuntu-latest
    env:
      GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
      BUILT_GEM_NAME: "govuk-design-system-rails-${{ github.ref_name }}.gem"
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - name: Yank
        run: |
          gem yank govuk-design-system-rails -v 0.10.1
          gem yank govuk-design-system-rails -v 0.10.2
          gem yank govuk-design-system-rails -v 0.10.3
